### ISSUE TITLE
Recipe Tags

### ISSUE THREAD

**Issue by ZNAXNOR** [ZNAXNOR/Recipe-Website#12]
### Tags
A tag is a label that categorizes a post with other, similar posts. Using the right tags makes it easier for the user to find the desired result.

## Tasks
- [x] A post can be equipped with multiple Tags.
- [x] The tagged post should be be displayed in its corresponding Tags groups after published.
- [ ] Users (except Admin) cannot view a tag with no posts.

---

## Main Features
- [x] **Tag groups and post types**
  - For each post type on the website, you can create multiple distinct tag groups. 
  - Once you set up the groups, you can tag each post type with a combination of tags from either single, multiple, or all groups.

- [x] **Adding same tags to multiple posts**
  - While browsing your site, site visitors can click on a tag to see all post types tagged with that term.
  -  If you add the same tag to multiple posts, the site visitors will see all published posts tagged with that term.

- [x] **Filter content by tags**
  - If you only choose tags from one group (Group A or Group B), the listing page will display posts tagged with _ANY_ of the terms you’ve selected.
  - If you choose tags from both groups, you will have the option to select _All tags_ or _Combination_.
  - All tags is more general. Published posts tagged with ANY of the terms you’ve chosen will display.
  - Combination is more specific. Published posts tagged with any combination of chosen terms from BOTH groups will display.
  - If you don’t choose any tags, the most recent posts for that listing page will display.
  - If there are no published posts on the site tagged with the terms you’ve chosen, no posts will display.

---

### References 

1. [University of Illinois Urbana-Champaign]

[University of Illinois Urbana-Champaign]: https://documentation.faa.illinois.edu/creating-and-editing-pages/adding-tags-filtering-content/#:~:text=Using%20tags%20on%20your%20site,by%20tag.
